// Builds linked lists of particles into the linked list dual grid.

#version 450

#include "particles.glsl"
#include "per_frame_resources.glsl"

void main() {
    uint particleIndex = gl_GlobalInvocationID.x;

    vec3 position = Particles[particleIndex].Position;
    ivec3 nearestDualGridCell = ivec3(position);

    // Invalid index is 0!
    uint prevParticleIndex = imageAtomicExchange(LinkedListDualGrid, nearestDualGridCell, particleIndex + 1) - 1;
    // todo
}